### ISSUE TITLE
Needed work in upstream opentelemetry-java-instrumentation

### ISSUE THREAD

**Issue by pavolloffay** [hypertrace/javaagent#216]
This outlines tasks that should be resolved in the upstream to support features in this repository or make maintenance easier:

- [ ] Make global ignore matcher configurable. It's needed to instrument streams from `java.io` package https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/1952 
- [ ] Share instrumentation context map across instrumentation modules. It is needed bc our stream instrumentation accesses objects created from HTTP/RPC instrumentations https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/1949
- [ ] Make packages used by muzzle configurable. It's needed if we want to use our own package, at the moment we use OTEL package names  https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/1395  
- [ ] Make loggig configurable e.g. to file https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/566 and https://github.com/hypertrace/javaagent/issues/172
- [ ] Build and publish muzzle plugin separately. Needed for  https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/1225
