### ISSUE TITLE
Roadmap for V1

### ISSUE THREAD

**Issue by pavolloffay** [hypertrace/javaagent#221]
This issue outlines a short term roadmap for reaching supportable V1. The instrumentation scope focuses on server-side frameworks and Spring Web. The server-side frameworks were chosen because this is where HT agent provides value for blocking and additional data capture.

Instrumentation:
- [ ] Spring Webflux instrumentation (via netty) https://github.com/hypertrace/javaagent/issues/206
- [ ] Micronaut instrumentation (via netty) https://github.com/hypertrace/javaagent/issues/207
- [ ] Netty client instrumentation https://github.com/hypertrace/javaagent/issues/215
- [ ] Spring web - Rest template https://github.com/hypertrace/javaagent/issues/214
- [ ] Struts https://github.com/hypertrace/javaagent/issues/218
- [ ] Armeria https://github.com/hypertrace/javaagent/issues/219

Testing:
- [ ] Abstract server tests https://github.com/hypertrace/javaagent/issues/99
- [ ] Abstract client tests https://github.com/hypertrace/javaagent/issues/98
- [ ] Smoke tests for servlet containers and make it pluggable https://github.com/hypertrace/javaagent/issues/217
- [ ] OPA filter smoke/contract tests https://github.com/hypertrace/javaagent/issues/157

Issues: 
- [ ] Test startup time and make sure HT agent does not drift from upstream https://github.com/hypertrace/javaagent/issues/212

Agent core:
* Log to file https://github.com/hypertrace/javaagent/issues/172
* HT agent size is 18 MB bigger than OTEL https://github.com/hypertrace/javaagent/issues/220
